-- Initial schema for vibecodingmvc
-- Tables: beer, beer_order, beer_order_line

-- BEER
CREATE TABLE IF NOT EXISTS beer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_name VARCHAR(255),
    beer_style VARCHAR(255),
    upc VARCHAR(255),
    quantity_on_hand INTEGER,
    price NUMERIC(19,2),
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- BEER_ORDER
CREATE TABLE IF NOT EXISTS beer_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    customer_ref VARCHAR(255),
    payment_amount NUMERIC(19,2),
    status VARCHAR(255),
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- BEER_ORDER_LINE
CREATE TABLE IF NOT EXISTS beer_order_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_order_id INTEGER NOT NULL,
    beer_id INTEGER NOT NULL,
    order_quantity INTEGER,
    quantity_allocated INTEGER,
    status VARCHAR(255),
    created_date TIMESTAMP,
    updated_date TIMESTAMP,
    CONSTRAINT fk_bol_order FOREIGN KEY (beer_order_id) REFERENCES beer_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_bol_beer FOREIGN KEY (beer_id) REFERENCES beer(id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_bol_order ON beer_order_line (beer_order_id);
CREATE INDEX IF NOT EXISTS idx_bol_beer ON beer_order_line (beer_id);
