-- Customers table migration
-- H2/Postgres-friendly DDL

CREATE TABLE IF NOT EXISTS customer (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER NOT NULL DEFAULT 0,
    name             VARCHAR(120) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    phone            VARCHAR(40),
    address_line1    VARCHAR(200) NOT NULL,
    address_line2    VARCHAR(200),
    city             VARCHAR(120),
    state            VARCHAR(80),
    postal_code      VARCHAR(20),
    created_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_email ON customer(email);
