-- Flyway migration: Create beer_order_shipment table
-- Note: Using INTEGER identity to match current JPA entity (BeerOrderShipment.id is Integer)
-- If you later migrate to UUIDs, add a follow-up migration accordingly.

CREATE TABLE IF NOT EXISTS beer_order_shipment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beer_order_id INT NOT NULL,
    shipment_status VARCHAR(50) NOT NULL,
    shipped_date TIMESTAMP NULL,
    tracking_number VARCHAR(255),
    carrier VARCHAR(255),
    notes VARCHAR(1000),
    created_date TIMESTAMP,
    updated_date TIMESTAMP,
    CONSTRAINT fk_bos_order FOREIGN KEY (beer_order_id) REFERENCES beer_order(id)
);

CREATE INDEX IF NOT EXISTS idx_bos_order ON beer_order_shipment(beer_order_id);
CREATE INDEX IF NOT EXISTS idx_bos_status ON beer_order_shipment(shipment_status);
